---
apiVersion: v1
kind: Namespace
metadata:
  name: farmiq-bi
  labels:
    name: farmiq-bi
    app.kubernetes.io/instance: farmiq
    app.kubernetes.io/version: v1
    app.kubernetes.io/managed-by: argocd
spec:
  finalizers:
  - kubernetes
